In [10]:
import numpy as np

def matrix_multiplication_2by2(a, b):
    multiplied = [[0, 0],
                  [0, 0]]
    
    multiplied[0][0] = a[0][0] * b[0][0] + a[0][1] * b[1][0]
    multiplied[0][1] = a[0][0] * b[0][1] + a[0][1] * b[1][1]
    multiplied[1][0] = a[1][0] * b[0][0] + a[1][1] * b[1][0]
    multiplied[1][1] = a[1][0] * b[0][1] + a[1][1] * b[1][1]

    return multiplied

mat1 = [[1, 2],
        [3, 4]]

mat2 = [[3, 5],
        [-2, 2]]

multiplied = matrix_multiplication_2by2(mat1, mat2)
print(multiplied)
print()

mat1arr = np.array(mat1)
mat2arr = np.array(mat2)

print(mat1arr @ mat2arr)

[[-1, 9], [1, 23]]

[[-1  9]
 [ 1 23]]


In [8]:
mat1 = [[1, 2],
        [3, 4]]

for i in range(len(mat1)):
    for j in range(len(mat1[0])):
        print(mat1[i][j])

1
2
3
4


In [5]:
l = []

print(l)
print(len(l))

l.append(12)
l.append([])
l.append(1.2)

print(l)
print(len(l))
print(l[1])


[]
0
[12, [], 1.2]
3
[]


In [13]:
def matrix_multiplication(a, b):
    multiplied = []

    n = len(a)

    if (n < 1):
        print("0 rows in matrix a")
        return multiplied
    
    m = len(a[0])

    if (m < 1):
        print("0 columns in matrix a")
        return multiplied

    k = len(b)

    if (k < 1):
        print("0 rows in matrix b")
        return multiplied

    l = len(b[0])

    if (l < 1):
        print("0 columns in matrix b")
        return multiplied

    if (m != k):
        print("Matrix size mismatch: ", m, k)
        return multiplied

    #output matrix n \times l
    for i in range(n):
        multiplied.append([])

        for j in range(l):
            s = 0

            for p in range(m):
                s += a[i][p] * b[p][j]
            
            multiplied[i].append(s)

    return multiplied

mat1 = [[1, 2],
        [3, 4],
        [3, -2],
        [5, 6]]

mat2 = [[3, 5, 8],
        [-2, 2, 9]]

multiplied = matrix_multiplication(mat1, mat2)
print(multiplied)
print()

mat1arr = np.array(mat1)
mat2arr = np.array(mat2)

print(mat1arr @ mat2arr)

[[-1, 9, 26], [1, 23, 60], [13, 11, 6], [3, 37, 94]]

[[-1  9 26]
 [ 1 23 60]
 [13 11  6]
 [ 3 37 94]]


$A \in \mathbb{R}^{n \times m}$

$B \in \mathbb{R}^{m \times k}$

$C \in \mathbb{R}^{n \times k}$

$C_{i, j} = \sum\limits_{p = 1}^{m} A_{i, p} B_{p, j}$

In [ ]:
!pip3 install opencv-python

In [28]:
import cv2

WIND_X, WIND_Y = 1100, 800

canvas = np.ones((WIND_Y, WIND_X, 3), np.uint8)# * 70

x, y = 200, 200
vx, vy = 3, 5
r = 90

while (True):
    canvas[:, :, :] = 80

    cv2.circle(canvas, (x, y), r, (223, 234, 112), -1)
    
    x += vx
    y += vy

    if (x + r >= WIND_X or x <= r):
        vx *= -1

    if (y + r >= WIND_Y or y <= r):
        vy *= -1

    cv2.imshow("window", canvas)

    key = cv2.waitKey(10) & 0xFF

    if (key == ord('q')):
        break

cv2.destroyAllWindows()
cv2.waitKey(50)

-1

In [18]:
canvas = np.ones((WIND_Y, WIND_X, 3), np.uint8) * 70

print(canvas.shape)

(800, 1100, 3)


In [42]:
import cv2

WIND_X, WIND_Y = 1100, 800

canvas = np.ones((WIND_Y, WIND_X, 3), np.uint8)# * 70

#creating new type
class Circle:
    def __init__(self, x, y, r, vx, vy, color, a = 0.05):
        self.x = x
        self.y = y
        self.vx = vx
        self.vy = vy
        self.a = a
        self.r = r
        self.color = color

    def draw(self, canvas):
        cv2.circle(canvas, (int(self.x), int(self.y)), self.r, self.color, -1)
    
    def move(self, WIND_X, WIND_Y):
        self.vy += self.a

        self.x += self.vx
        self.y += self.vy

        if (self.x + self.r >= WIND_X or self.x <= self.r):
            self.vx *= -1

        if (self.y + self.r >= WIND_Y or self.y <= self.r):
            self.vy += self.a
            self.vy *= -1

#creating an instance of this new type
x, y = 200, 200
vx, vy = 3, 5
r = 90
color = (223, 234, 112)

#circle_1 = Circle(x, y, r, vx, vy, color)
#circle_2 = Circle(300, 400, 50, 6, 7, (52, 23, 34))

circles = []

while (True):
    #canvas[:, :, :] = 80
    canvas = cv2.addWeighted(canvas, 0.95, canvas, 0, 0)

    #circle_1.move(WIND_X, WIND_Y)
    #circle_1.draw(canvas)
    #circle_2.move(WIND_X, WIND_Y)
    #circle_2.draw(canvas)

    for circle in circles:
        circle.move(WIND_X, WIND_Y)

    for circle in circles:
        circle.draw(canvas)

    cv2.imshow("window", canvas)

    key = cv2.waitKey(10) & 0xFF

    if (key == ord('n')):
        circles.append(Circle(300, 400, 5 + np.random.randint(8),
                              np.random.randint(1), np.random.randint(7),
                              (np.random.randint(255), np.random.randint(255), np.random.randint(255))))

    if (key == ord('d')):
        if (len(circles) > 0):
            circles.pop()

    if (key == ord('q')):
        break

cv2.destroyAllWindows()
cv2.waitKey(50)

-1